feat!: Upgrade to casper-js-sdk 5.x
make-software/ces-js-parser pull request #27
Opened 2024-12-19 13:16 UTC by Volodymyr-Kuchinskyi

2024-12-19 17:16 UTC, ihor commented on package.json
> +    "casper-js-sdk": "^5.0.0-rc8"
We'll release `5.0.0-beta1` tomorrow. Let's use it.

2024-12-19 17:17 UTC, ihor commented on src/event.ts
> +import { toBytesString } from "casper-js-sdk/dist/types/ByteConverters";
Why do we have `dist` in the path? This doesn't seem correct

2025-01-24 14:11 UTC, ihor requested changes
@Volodymyr-Kuchinskyi please address the comment, update the SDK version to the latest, and add a test with Casper 2.0 `Transactions`

2025-02-27 08:04 UTC, ihor approved these changes

2025-02-27 11:47 UTC, Volodymyr-Kuchinskyi commented
Waiting for casper-js-sdk 5.0.12-beta2 [https://github.com/casper-ecosystem/casper-js-sdk/tree/5.0.11-beta2](https://github.com/casper-ecosystem/casper-js-sdk/tree/5.0.11-beta2)

2025-02-28 15:22 UTC, merged